### ISSUE TITLE
Where are the instructions for running the nativescript project?

### ISSUE THREAD

**Issue by nigel-dewar** [JonnyBGod/angular2-webpack-advance-starter#10]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angular2-webpack-advance-starter/Lobby)

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository

Hi There, I had a read over instructions a few times, but I cannot find instructions for running the
nativescript app. 

please advise?

Cheers

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by nigel-dewar** [comment]
Oh sorry never mind I found them in the package.json file under nativescript folder.

cheers

**Comment by JonnyBGod** [comment]
Nativescript is not working for now. I am waiting for NS team to finish the port to webpack.

**Comment by DanielKucal** [comment]
@JonnyBGod, any news on this topic?
