### ISSUE TITLE
(electron:production): css relative paths

### ISSUE THREAD

**Issue by JonnyBGod** [JonnyBGod/angular2-webpack-advance-starter#4]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**

bug
- **What is the current behavior?**

In electron production env:

``` css
:host .class {
    background: url('path/to/file.jpg');
}
```

end up:

```
file:///path/to/file.jpg
```

Basically is being searched relative to the OS root folder.
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
  https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

```
npm run build:desktop
```
- **What is the expected behavior?**

The files should be searched relative to the current app folder.
- **What is the motivation / use case for changing the behavior?**

Ease of use and cohesion between different apps.
- **Please tell us about your environment:**
- Angular version: 2.1.0-beta.0
- Electron [Mac]
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by michaeljota** [comment]
Hi!

I use the [ng2-admin](https://github.com/akveo/ng2-admin), with my own [Electron integration](https://github.com/michaeljota/ng2-admin). 

They use variables to load images and fonts in their sass files, as [this](https://github.com/akveo/ng2-admin/blob/master/src/app/theme/sass/conf/_variables.scss).

This may help, but I'm not sure how or where you would set it up in your current workflow.

**Comment by JonnyBGod** [comment]
@michaeljota you can use variables. Because of the isolated nature of css in angular components you should ```@import '../../../variables.scss';``` at the beginning of each scss file you want to have the variables available.

**Comment by michaeljota** [comment]
Yeah, I mean. I can integrate this in my own workflow, but was thinking more about this as a solution to your current issue.
