### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by michaeljota** [JonnyBGod/angular2-webpack-advance-starter#7]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angular2-webpack-advance-starter/Lobby)
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
- **Do you want to request a _feature_ or report a _bug_?**

feature (why ask twice?)
- **What is the current behavior?**

modules and scripts working in *nix SO. 
- **What is the expected behavior?**

modules and scripts cross platform. 
- **What is the motivation / use case for changing the behavior?**

I use Windows to develop, shame on me.
- **Please tell us about your environment:**
- SO: Windows 10
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

related: 
[fs-xattr #15](https://github.com/LinusU/fs-xattr/issues/15)
[fs-xattr #16](https://github.com/LinusU/fs-xattr/issues/16)

Yeah, besides the scripts ( #1 ) this module fails installing on Windows. Why do you use this for?

**Comment by JonnyBGod** [comment]
thanks for the report.

Unfortunately I do not have a windows computer atm. Will try to fix this as soon as possible but would be much faster if I could get some help from an experienced windows developer.

**Comment by michaeljota** [comment]
I'm not an "experienced" Windows developer. Just a regular Windows developer. I can assist you if you with this. I'm interested in making a multiplatform seed for my Angular2 projects. 😀
