### ISSUE TITLE
Getting error when running project 

### ISSUE THREAD

**Issue by nigel-dewar** [JonnyBGod/angular2-webpack-advance-starter#9]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angular2-webpack-advance-starter/Lobby)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

I am windows 7 SP1 64bit.
using npm@3.3.12
using node@v5.5.0

I ran npm install
then npm run. project seems to run but then says 

          [] -> factory:56ms building:3024ms = 3080ms
     [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 506 bytes {0} [built]
            [] -> factory:88ms building:70ms = 158ms
     [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 548 bytes {0} [built]
            [] -> factory:89ms building:95ms = 184ms
webpack: bundle is now VALID.
[default] C:\test\angular2-webpack-advance-starter\src\app\frameworks\analytics\services\analytics.service.ts:6:24
    Module '"C:/test/angular2-webpack-advance-starter/node_modules/angulartics2/index"' has no exported member 'Angulartics2Goo
gleAnalytics'.
[default] Checking finished with 1 errors, saying cannot find this module and that.

When I try to view app in browser using localhost:3000, app hangs on loading screen with HEAPS of errors in console.

I think some kind of error is preventing webpack from building all the stuff it needs.

do you have an idea about what might be causing this behaviour?

Cheers

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by nigel-dewar** [comment]
Sorry I found that a manual install of analytics2 was required for some reason. I have fixed it. prob my fault for using a dam windows machine, I should be using a mac.

cheers

Nigel

**Comment by JonnyBGod** [comment]
Cool. I don't have a windows machine to test atm, please let me know if you find any problems running it on windows, I will try to help you out.
